apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
  namespace: project-d1
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    app: spring-boot-app
