apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-event-deploy-latest
  namespace: caps
spec:
  selector:
    matchLabels:
      app: react-event-app-latest
  template:
    metadata:
      labels:
        app: react-event-app-latest
    spec:
      containers:
        - name: react-event-app-latest
          image: yogeshpri/testimg:v2
          ports:
            - containerPort: 80
