apiVersion: v1
kind: Service
metadata:
  name: react-event-service
  namespace: project-d1
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
  selector:
    app: react-event-app-latest
