apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-deploy
  namespace: caps
spec:
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
        - name: spring-boot-app
          image: yogeshpri/testimagback:1.0.0
          ports:
            - containerPort: 80
