apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-deploy
  namespace: project-d1
spec:
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
        - name: spring-boot-app
          image: prashanth7993/backend:v5
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/EventManagement
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
          ports:
            - containerPort: 8080
